version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DimpgP21
      POSTGRES_DB: postgres
    ports:
      - 5435:5432
    volumes:
      - /Users/janine/backup/pgdata:/var/lib/postgresql/data

  amcadmin:
    image: amcadministration
    ports: 
      - "3050:3050"  
    environment:
      - NODE_ENV=development
    depends_on:
      - db


